export const GET_VEGPRODUCTS_REQUEST = "GET_VEGPRODUCTS_REQUEST";
export const GET_VEGPRODUCTS_SUCCESS = "GET_VEGPRODUCTS_SUCCESS";
export const GET_VEGPRODUCTS_FAIL = "GET_VEGPRODUCTS_FAIL";

export const GET_GROCPRODUCTS_REQUEST = "GET_GROCPRODUCTS_REQUEST";
export const GET_GROCPRODUCTS_SUCCESS = "GET_GROCPRODUCTS_SUCCESS";
export const GET_GROCPRODUCTS_FAIL = "GET_GROCPRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";
